//
//  ShareCardView.swift
//  LeBronify
//
//  Created by Robert Wiscount on 3/26/25.
//

import SwiftUI

// MARK: - Starting 5 Card (the shareable image)

struct Starting5CardView: View {
    let songs: [Song]
    let totalPlays: Int

    private let positions = ["PG", "SG", "SF", "PF", "C"]
    private let cardBg = Color(red: 0.08, green: 0.08, blue: 0.08)

    var body: some View {
        VStack(spacing: 0) {
            // Header
            VStack(spacing: 4) {
                Text("MY STARTING 5")
                    .font(.system(size: 24, weight: .black))
                    .foregroundColor(.yellow)
                    .tracking(2)

                Text("LEBRONIFY")
                    .font(.system(size: 11, weight: .bold))
                    .foregroundColor(.white.opacity(0.4))
                    .tracking(3)
            }
            .padding(.top, 24)
            .padding(.bottom, 16)

            // Divider line
            Rectangle()
                .fill(Color.yellow.opacity(0.3))
                .frame(height: 1)
                .padding(.horizontal, 20)

            // Song rows
            VStack(spacing: 0) {
                ForEach(Array(songs.prefix(5).enumerated()), id: \.element.id) { index, song in
                    HStack(spacing: 14) {
                        // Position badge
                        Text(positions[index])
                            .font(.system(size: 13, weight: .black, design: .monospaced))
                            .foregroundColor(.black)
                            .frame(width: 32, height: 32)
                            .background(Color.yellow)
                            .cornerRadius(6)

                        // Album art
                        Image(song.albumArt)
                            .resizable()
                            .aspectRatio(contentMode: .fill)
                            .frame(width: 44, height: 44)
                            .cornerRadius(4)

                        // Song info
                        VStack(alignment: .leading, spacing: 2) {
                            Text(song.title)
                                .font(.system(size: 14, weight: .bold))
                                .foregroundColor(.white)
                                .lineLimit(1)

                            Text(song.artist)
                                .font(.system(size: 11))
                                .foregroundColor(.white.opacity(0.5))
                                .lineLimit(1)
                        }

                        Spacer()

                        // Play count
                        VStack(alignment: .trailing, spacing: 1) {
                            Text("\(song.playCount)")
                                .font(.system(size: 18, weight: .black, design: .monospaced))
                                .foregroundColor(.yellow)
                            Text("plays")
                                .font(.system(size: 9, weight: .medium))
                                .foregroundColor(.white.opacity(0.4))
                        }
                    }
                    .padding(.horizontal, 20)
                    .padding(.vertical, 12)

                    if index < min(songs.count, 5) - 1 {
                        Rectangle()
                            .fill(Color.white.opacity(0.06))
                            .frame(height: 1)
                            .padding(.horizontal, 20)
                    }
                }
            }
            .padding(.top, 8)

            // Total plays footer
            Rectangle()
                .fill(Color.yellow.opacity(0.3))
                .frame(height: 1)
                .padding(.horizontal, 20)
                .padding(.top, 8)

            HStack {
                Text("TOTAL PLAYS")
                    .font(.system(size: 11, weight: .heavy))
                    .foregroundColor(.white.opacity(0.5))
                    .tracking(1)
                Spacer()
                Text("\(totalPlays)")
                    .font(.system(size: 22, weight: .black, design: .monospaced))
                    .foregroundColor(.yellow)
            }
            .padding(.horizontal, 20)
            .padding(.vertical, 12)

            // Footer branding
            Text("Generated by LeBronify")
                .font(.system(size: 10, weight: .medium))
                .foregroundColor(.white.opacity(0.25))
                .padding(.bottom, 16)
        }
        .frame(width: 390)
        .background(cardBg)
        .cornerRadius(16)
        .overlay(
            RoundedRectangle(cornerRadius: 16)
                .stroke(Color.yellow.opacity(0.2), lineWidth: 1)
        )
    }
}

// MARK: - Share Card Generator View

struct ShareCardGeneratorView: View {
    @EnvironmentObject var viewModel: LeBronifyViewModel
    @State private var showingShareSheet = false
    @State private var shareImage: UIImage?
    @State private var cachedSongs: [Song] = []
    @State private var cachedTotalPlays: Int = 0
    @Environment(\.dismiss) var dismiss

    private let bgColor = Color(red: 0.07, green: 0.07, blue: 0.07)

    var body: some View {
        NavigationView {
            ZStack {
                bgColor.ignoresSafeArea()

                if cachedSongs.isEmpty {
                    ProgressView()
                        .tint(.yellow)
                } else {
                    ScrollView {
                        VStack(spacing: 24) {
                            Text("Your top 5 most-played songs,\nstyled like an ESPN stat card.")
                                .font(.system(size: 14))
                                .foregroundColor(.white.opacity(0.5))
                                .multilineTextAlignment(.center)
                                .padding(.top, 8)

                            // Card preview
                            Starting5CardView(songs: cachedSongs, totalPlays: cachedTotalPlays)
                                .padding(.horizontal, 16)

                            // Share button
                            Button {
                                generateAndShare()
                            } label: {
                                HStack(spacing: 8) {
                                    Image(systemName: "square.and.arrow.up")
                                    Text("Share My Starting 5")
                                }
                                .font(.system(size: 16, weight: .bold))
                                .foregroundColor(.black)
                                .padding(.horizontal, 32)
                                .padding(.vertical, 14)
                                .background(Color.yellow)
                                .cornerRadius(25)
                            }

                            Spacer().frame(height: 40)
                        }
                    }
                }
            }
            .navigationTitle("My Starting 5")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .navigationBarLeading) {
                    Button("Done") { dismiss() }
                        .foregroundColor(.yellow)
                }
            }
            .sheet(isPresented: $showingShareSheet) {
                if let image = shareImage {
                    ShareSheet(items: [image])
                }
            }
            .onAppear {
                cachedSongs = Array(viewModel.allSongs
                    .sorted { $0.playCount > $1.playCount }
                    .prefix(5))
                cachedTotalPlays = viewModel.allSongs.reduce(0) { $0 + $1.playCount }
            }
        }
        .preferredColorScheme(.dark)
    }

    @MainActor
    private func generateAndShare() {
        let cardView = Starting5CardView(songs: cachedSongs, totalPlays: cachedTotalPlays)
        let renderer = ImageRenderer(content: cardView.frame(width: 390))
        renderer.scale = UIScreen.main.scale

        if let image = renderer.uiImage {
            shareImage = image
            showingShareSheet = true
        }
    }
}

// MARK: - Share Sheet (UIActivityViewController wrapper)

struct ShareSheet: UIViewControllerRepresentable {
    let items: [Any]

    func makeUIViewController(context: Context) -> UIActivityViewController {
        UIActivityViewController(activityItems: items, applicationActivities: nil)
    }

    func updateUIViewController(_ uiViewController: UIActivityViewController, context: Context) {}
}
